# Generated by Django 3.1.14 on 2022-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True, verbose_name='Company Name')),
                ('inn_company', models.CharField(max_length=20, null=True)),
                ('chief', models.CharField(max_length=255, null=True, verbose_name='Chief')),
                ('phone_company', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
