# Generated by Django 3.1.14 on 2022-05-19 10:59

from django.db import migrations

def create_data(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    Company(companyName="Company", inn_company="INN Company", chief="Chief", phone_company="000000000").save()
class Migration(migrations.Migration):


    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
